package com.desafio.desenvolvedor.backend.servicorest.helpers;

public enum GeneroEnum {

	ACAO, ANIMACAO,	AVENTURA, ARTE,	CHANCHADA, CATASTROFE, COMEDIA,	COMEDIA_ROMANTICA, DANÇA, DOCUMENTARIO,	FICCAO, DRAMA,
	FAROESTE, GUERRA, MUSICAL, POLICIAL, ROMANCE, SERIADO, SUSPENSE, TERROR;
}
